repo:
  repoUrl: file:///opt/kamu/workspace/.kamu/datasets
auth:
  providers:
    # Dummy accounts for owners of example datasets
    - kind: password
      accounts:
        - accountName: kamu
          avatarUrl: https://avatars.githubusercontent.com/u/50896974?s=200&v=4
        - accountName: sh101-bowen
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: sh102-gambier
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: sh103-howe
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: sh104-granville
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: sh105-keats
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: sh106-seymour
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: mim.dk
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3530/3530558.png
        - accountName: mmo.gov.uk
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3530/3530558.png
        - accountName: moa.gov.nl
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3530/3530558.png
        - accountName: ofb.gouv.fr
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3530/3530558.png
        - accountName: protectedseas.net
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3530/3530558.png
        - accountName: acme.fishing.co
          avatarUrl: https://cdn-icons-png.flaticon.com/512/1090/1090630.png
        - accountName: globalfishingwatch.org
          avatarUrl: https://cdn-icons-png.flaticon.com/512/744/744480.png
        - accountName: bmis-bycatch.org
          avatarUrl: https://cdn-icons-png.flaticon.com/128/10197/10197245.png
    - kind: github
