import {UserInterface} from '../interface/auth.interface';
export const userResponse: UserInterface = {
  login: 'kulykivska',
  id: 87068546,
  node_id: 'MDQ6VXNlcjg3MDY4NTQ2',
  avatarUrl: 'https://avatars.githubusercontent.com/u/87068546?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/kulykivska',
  html_url: 'https://github.com/kulykivska',
  followers_url: 'https://api.github.com/users/kulykivska/followers',
  following_url: 'https://api.github.com/users/kulykivska/following{/other_user}',
  gists_url: 'https://api.github.com/users/kulykivska/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/kulykivska/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/kulykivska/subscriptions',
  organizations_url: 'https://api.github.com/users/kulykivska/orgs',
  repos_url: 'https://api.github.com/users/kulykivska/repos',
  events_url: 'https://api.github.com/users/kulykivska/events{/privacy}',
  received_events_url: 'https://api.github.com/users/kulykivska/received_events',
  type: 'User',
  site_admin: false,
  name: 'Kulykivska Julia',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 0,
  public_gists: 0,
  followers: 2,
  following: 7,
  created_at: '2021-07-07T09:51:41Z',
  updated_at: '2021-11-09T13:16:42Z'
};
