[workspace]
members = ["api-server"]


[workspace.dependencies]
# Kamu
dill = "0.5"
opendatafabric = { git = "https://github.com/kamu-data/kamu-cli", tag = "v0.122.0" }
kamu = { git = "https://github.com/kamu-data/kamu-cli", tag = "v0.122.0" }
kamu-adapter-graphql = { git = "https://github.com/kamu-data/kamu-cli", tag = "v0.122.0" }
kamu-adapter-http = { git = "https://github.com/kamu-data/kamu-cli", tag = "v0.122.0" }
