[bans]
# Forbid multiple versions of same dependency (with some exceptions)
# TODO: Change to "deny" once we crack down on duplication
multiple-versions = "warn"
# Avoid adding dependencies to this list as this slows down compilation.
# Find another ways to avoid duplication.
skip-tree = []

# We should always specify version ranges
wildcards = "deny"

# We specify features explicitly to avoid bloat
workspace-default-features = "deny"
features = []

deny = [
    # Crates we shouldn't use
    { name = "openssl-sys", reason = "Configure `rustls` instead" },

    # Creates we deny multiple versions of (until we flip to skip-tree)
    { name = "arrow", deny-multiple-versions = true },
    { name = "axum", deny-multiple-versions = true },
    { name = "datafusion", deny-multiple-versions = true },
    # { name = "rustls", deny-multiple-versions = true },
    { name = "tokio", deny-multiple-versions = true },
    { name = "tonic", deny-multiple-versions = true },
]


[licenses]
version = 2
allow = [
    "Apache-2.0",
    "CC0-1.0",
    "0BSD",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Unlicense",
    "Zlib",
]
private = { ignore = true }

[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
name = "unicode-ident"


[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]


[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-org = { github = ["kamu-data"] }


[advisories]
version = 2
ignore = []
