[package]
name = "kamu-api-server"
version = "0.1.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2018"

[dependencies]
# Kamu
opendatafabric = { git = "https://github.com/kamu-data/kamu-cli", branch = "master" }
# opendatafabric = { path = "../../kamu-cli/opendatafabric" }
kamu = { git = "https://github.com/kamu-data/kamu-cli", branch = "master" }
# kamu = { path = "../../kamu-cli/kamu-core" }
dill = { version = "~0.2.0" }
# dill = { path = "../../dill" }

# HTTP
actix-web = "*"
actix-cors = "*"

# GraphQL
async-graphql = { version = "*", features = ["chrono", "url", "apollo_tracing"] }
async-graphql-actix-web = "*"

# Tracing / logging / telemetry
tracing = "*"  
tracing-subscriber = "*"
tracing-log = "*"
tracing-bunyan-formatter = "*"
tracing-actix-web = "*"

# Utils
chrono = "*"
clap = "*"
indoc = "*"
serde = "*"
serde_json = "*"
tokio = { version = "*", features = ["macros"] }
url = "*"


[dev-dependencies]
kamu-test = { git = "https://github.com/kamu-data/kamu-cli", branch = "master" }
# kamu-test = { path = "../../kamu-cli/kamu-core-test" }
tempfile = "*"
