[package]
name = "kamu-api-server"
version = "0.1.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2018"

[dependencies]
# Kamu
opendatafabric = { git = "https://github.com/kamu-data/kamu-cli", branch = "master" }

# HTTP
actix-web = "*"
actix-cors = "*"

# GraphQL
async-graphql = { version = "*", features = ["chrono", "url", "apollo_tracing"] }
async-graphql-actix-web = "*"

# Tracing / logging / telemetry
tracing = "*"  
tracing-subscriber = "*"
tracing-log = "*"
tracing-bunyan-formatter = "*"
tracing-actix-web = "*"

# Utils
chrono = "*"
clap = "*"
indoc = "*"
serde = "*"
serde_json = "*"
tokio = { version = "*", features = ["macros"] }
