[package]
name = "kamu-api-server"
version = "0.1.0"
authors = ["Sergii Mikhtoniuk <mikhtoniuk@gmail.com>"]
edition = "2018"

[dependencies]
# Kamu
dill = { version = "~0.2.0" }
opendatafabric = { git = "https://github.com/kamu-data/kamu-cli", branch = "master" }
kamu = { git = "https://github.com/kamu-data/kamu-cli", branch = "master" }

# Kamu (dev)
# dill = { path = "../../dill" }
# opendatafabric = { path = "../../kamu-cli/opendatafabric" }
# kamu = { path = "../../kamu-cli/kamu-core" }

# HTTP
actix-web = "*"
actix-cors = "*"
reqwest = { version = "*", features = ["blocking", "json"] }  # TODO: Use non-blocking after switching to tokio 1.0

# GraphQL
async-graphql = { version = "*", features = ["chrono", "url", "apollo_tracing"] }
async-graphql-actix-web = "*"

# Tracing / logging / telemetry
tracing = "*"  
tracing-subscriber = { version = "*", features = ["env-filter"] }
tracing-log = "*"
tracing-bunyan-formatter = "*"
tracing-actix-web = "*"

# Utils
chrono = "*"
clap = "*"
indoc = "*"
serde = "*"
serde_json = "*"
tokio = { version = "*", features = ["macros"] }
url = "*"


[dev-dependencies]
tempfile = "*"
