repo:
  repoUrl: file:///opt/kamu/workspace/.kamu/datasets
auth:
  didEncryption:
    enabled: true
    encryptionKey: hUuFbsNDOr9Gq6iRpCpilCueBaBWwbzM
  providers:
    # Dummy accounts for owners of example datasets
    - kind: password
      accounts:
        - accountName: kamu
          email: support+kamu@kamu.dev
          avatarUrl: https://avatars.githubusercontent.com/u/50896974?s=200&v=4
        - accountName: sh101-bowen
          email: support+sh101-bowen@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: sh102-gambier
          email: support+sh102-gambier@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: sh103-howe
          email: support+sh103-howe@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: sh104-granville
          email: support+sh104-granville@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: sh105-keats
          email: support+sh105-keats@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: sh106-seymour
          email: support+sh106-seymour@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3118/3118054.png
        - accountName: mim.dk
          email: support+mim.dk@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3530/3530558.png
        - accountName: mmo.gov.uk
          email: support+mmo.gov.uk@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3530/3530558.png
        - accountName: moa.gov.nl
          email: support+moa.gov.nl@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3530/3530558.png
        - accountName: ofb.gouv.fr
          email: support+ofb.gouv.fr@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3530/3530558.png
        - accountName: protectedseas.net
          email: support+protectedseas.net@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/3530/3530558.png
        - accountName: acme.fishing.co
          email: support+acme.fishing.co@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/1090/1090630.png
        - accountName: globalfishingwatch.org
          email: support+globalfishingwatch.org@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/512/744/744480.png
        - accountName: bmis-bycatch.org
          email: support+bmis-bycatch.org@kamu.dev
          avatarUrl: https://cdn-icons-png.flaticon.com/128/10197/10197245.png
    - kind: github
datasetEnvVars:
  enabled: true
  encryptionKey: QfnEDcnUtGSW2pwVXaFPvZOwxyFm2BOC
