type Query {
	"""
	Returns the version of the GQL API
	"""
	apiVersion: String!
	"""
	Returns dataset by its ID
	"""
	datasetById(id: DatasetID!): Dataset
	"""
	Iterates all datasets
	"""
	datasets(after: String, before: String, first: Int, last: Int): DatasetConnection!
}
scalar DatasetID
type Dataset {
	id: DatasetID!
	"""
	Access to the temporal metadata of the dataset
	"""
	metadataChain: MetadataChain!
}
type MetadataChain {
	"""
	Returns a metadata block corresponding to the specified hash
	"""
	blockByHash(hash: Sha3256!): MetadataBlock
	"""
	Iterates all metadata blocks starting from the latest one
	"""
	blocks(after: String, before: String, first: Int, last: Int): MetadataBlockConnection!
}
scalar Sha3256
type MetadataBlock {
	blockHash: Sha3256!
	prevBlockHash: Sha3256
	systemTime: DateTime!
	outputWatermark: DateTime
}
"""
Implement the DateTime<Utc> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime
type MetadataBlockConnection {
	"""
	Information to aid in pagination.
	"""
	pageInfo: PageInfo!
	"""
	A list of edges.
	"""
	edges: [MetadataBlockEdge]
}
"""
Information about pagination in a connection
"""
type PageInfo {
	"""
	When paginating backwards, are there more items?
	"""
	hasPreviousPage: Boolean!
	"""
	When paginating forwards, are there more items?
	"""
	hasNextPage: Boolean!
	"""
	When paginating backwards, the cursor to continue.
	"""
	startCursor: String
	"""
	When paginating forwards, the cursor to continue.
	"""
	endCursor: String
}
"""
An edge in a connection.
"""
type MetadataBlockEdge {
	"""
	The item at the end of the edge
	"""
	node: MetadataBlock!
	"""
	A cursor for use in pagination
	"""
	cursor: String!
}
type DatasetConnection {
	"""
	Information to aid in pagination.
	"""
	pageInfo: PageInfo!
	"""
	A list of edges.
	"""
	edges: [DatasetEdge]
}
"""
An edge in a connection.
"""
type DatasetEdge {
	"""
	The item at the end of the edge
	"""
	node: Dataset!
	"""
	A cursor for use in pagination
	"""
	cursor: String!
}
schema {
	query: Query
}
