type BlockRef {
	name: String!
	blockHash: Sha3256!
}
type Dataset {
	id: DatasetID!
	"""
	Access to the temporal metadata of the dataset
	"""
	metadataChain: MetadataChain!
	"""
	Creation time of the most recent metadata block in the chain
	"""
	lastUpdatedAt: DateTime!
	"""
	Creation time of the first metadata block in the chain
	"""
	createdAt: DateTime!
	"""
	Total number of output records in this dataset
	"""
	numRecordsTotal: Int!
	"""
	Records with event time prior to the watermark have already been reflected in the dataset (with high degree of certainty, but not guaranteed)
	"""
	lastWatermark: DateTime
	"""
	An estimated size of data on disk not accounting for replication or caching
	"""
	dataSize: Int!
}
type DatasetConnection {
	"""
	Information to aid in pagination.
	"""
	pageInfo: PageInfo!
	"""
	A list of edges.
	"""
	edges: [DatasetEdge]
}
"""
An edge in a connection.
"""
type DatasetEdge {
	"""
	The item at the end of the edge
	"""
	node: Dataset!
	"""
	A cursor for use in pagination
	"""
	cursor: String!
}
scalar DatasetID
type Datasets {
	"""
	Returns dataset by its ID
	"""
	byId(id: DatasetID!): Dataset
	"""
	Iterates all datasets
	"""
	all(after: String, before: String, first: Int, last: Int): DatasetConnection!
}
"""
Implement the DateTime<Utc> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime
type MetadataBlock {
	blockHash: Sha3256!
	prevBlockHash: Sha3256
	systemTime: DateTime!
	outputWatermark: DateTime
}
type MetadataBlockConnection {
	"""
	Information to aid in pagination.
	"""
	pageInfo: PageInfo!
	"""
	A list of edges.
	"""
	edges: [MetadataBlockEdge]
}
"""
An edge in a connection.
"""
type MetadataBlockEdge {
	"""
	The item at the end of the edge
	"""
	node: MetadataBlock!
	"""
	A cursor for use in pagination
	"""
	cursor: String!
}
type MetadataChain {
	"""
	Returns all named metadata block references
	"""
	refs: [BlockRef!]!
	"""
	Returns a metadata block corresponding to the specified hash
	"""
	blockByHash(hash: Sha3256!): MetadataBlock
	"""
	Iterates all metadata blocks starting from the latest one
	"""
	blocks(after: String, before: String, first: Int, last: Int): MetadataBlockConnection!
}
"""
Information about pagination in a connection
"""
type PageInfo {
	"""
	When paginating backwards, are there more items?
	"""
	hasPreviousPage: Boolean!
	"""
	When paginating forwards, are there more items?
	"""
	hasNextPage: Boolean!
	"""
	When paginating backwards, the cursor to continue.
	"""
	startCursor: String
	"""
	When paginating forwards, the cursor to continue.
	"""
	endCursor: String
}
type Query {
	"""
	Returns the version of the GQL API
	"""
	apiVersion: String!
	"""
	Dataset-related functionality group
	"""
	datasets: Datasets!
	"""
	Search-related functionality group
	"""
	search: Search!
}
type Search {
	"""
	Perform search across all resources
	"""
	query(after: String, before: String, first: Int, last: Int, query: String!): SearchQueryResultConnection!
}
union SearchQueryResult = | Dataset
type SearchQueryResultConnection {
	"""
	Information to aid in pagination.
	"""
	pageInfo: PageInfo!
	"""
	A list of edges.
	"""
	edges: [SearchQueryResultEdge]
}
"""
An edge in a connection.
"""
type SearchQueryResultEdge {
	"""
	The item at the end of the edge
	"""
	node: SearchQueryResult!
	"""
	A cursor for use in pagination
	"""
	cursor: String!
}
scalar Sha3256
schema {
	query: Query
}
