[package]
name = "kamu-oracle-provider"
description = "Oracle provider that uses Kamu Node to supply data to blockchain smart contracts"
version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
readme = { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }


[lints]
workspace = true


[lib]
doctest = false


[dependencies]
graceful-shutdown = { workspace = true, default-features = false }
observability = { workspace = true, default-features = false, features = [
    "dill",
    "opentelemetry",
    "prometheus",
] }
odf = { workspace = true, default-features = false }

# TODO: alloy is pinned until datafusion & object_store upgrade to reqwest v13
alloy = { version = "~1.7.3", default-features = false, features = [
    "contract",
    "network",
    "node-bindings",
    "provider-http",
    "provider-ws",
    "reqwest-rustls-tls",
    "rpc-types-eth",
    "signer-local",
    "sol-types",
    "std",
] }
async-trait = { version = "0.1", default-features = false }
axum = { version = "0.8", default-features = false, features = [
    "http1",
    "tokio",
] }
chrono = { version = "0.4", default-features = false }
ciborium = { version = "0.2", default-features = false }
clap = { version = "4", default-features = false, features = [
    "cargo",
    "color",
    "derive",
    "error-context",
    "help",
    "std",
    "suggestions",
    "usage",
    # "env",
    "wrap_help",
] }
dill = { version = "0.17", default-features = false }
hex = { version = "0.4" }
http = { version = "1", default-features = false }
internal-error = { workspace = true }
prometheus = { version = "0.14", default-features = false }
reqwest = { version = "0.12", default-features = false, features = [
    "brotli",
    "deflate",
    "gzip",
    "json",
    "rustls-tls-webpki-roots",
] }
rustls = { version = "0.23", default-features = false, features = [
    "aws-lc-rs",
] }
serde = { version = "1", default-features = false, features = [
    "derive",
] }
serde_json = { version = "1", default-features = false }
setty = { version = "1", features = [
    "case-enums-any",
    "case-enums-pascal",
    "case-fields-camel",
    "derive-clone",
    "derive-debug",
    "derive-deserialize",
    "derive-jsonschema",
    "derive-partial-eq",
    "derive-serialize",
    "fmt-json",
    "fmt-yaml",
    "gen-jsonschema",
    "gen-markdown",
    "types-chrono",
    "types-duration-string",
    "types-url",
] }
strum = { version = "0.28", default-features = false, features = [
    "derive",
    "std",
] }
thiserror = { version = "2", default-features = false }
tokio = { version = "1", default-features = false, features = [
    "macros",
    "rt",
    "rt-multi-thread",
] }
tracing = { version = "0.1", default-features = false, features = [
] }
url = { version = "2", default-features = false, features = [
    "serde",
] }


[dev-dependencies]
test-group = { version = "1" }
test-log = { version = "0.2", features = [
    "trace",
] }
