name: build
on: [push]
env:
  RUST_BACKTRACE: "1"
jobs:
  check_fmt:
    name: Check / Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1 # Uses rust-toolchain file
        with:
          components: rustfmt
      - name: cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

  test_linux:
    name: Test / Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1  # Uses rust-toolchain file
      - run: cargo build
      - run: cargo test --verbose
      - run: git diff
      - run: git diff-index --quiet HEAD  # Ensure all generated files are up-to-date
