name: build
on: [push]
env:
  RUST_BACKTRACE: "1"
jobs:
  test_linux:
    name: Test / Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1  # Uses rust-toolchain file
        with:
          components: rustfmt
      - run: cargo build
      - run: cargo test --verbose
      - run: git diff
      - run: git diff-index --quiet HEAD  # Ensure all generated files are up-to-date
