name: release-images
on:
  # Manual trigger
  workflow_dispatch: {}
  # Automatic trigger after each release
  # Note: Triggers on both successes and failures (see conditional below)
  workflow_run:
    workflows:
      - release
    types:
      - completed
jobs:
  build_images:
    name: Build Images
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event.workflow_run.conclusion == null
    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout the same commit that the release was built for
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build api-server image
        run: |
          cd images/
          make api-server
      
      - name: Build oracle-provider image
        run: |
          cd images/
          make oracle-provider
      
      - name: Publish base images
        run: |
          cd images/
          make api-server-push
          make oracle-provider-push

      - name: Build images with sample data
        run: |
          cd images/
          make api-server-with-data
          make api-server-with-data-mt

      - name: Publish auxiliary images
        run: |
          cd images/
          make api-server-with-data-push
          make api-server-with-data-mt-push
