name: release-images
on:
  # Manual trigger
  workflow_dispatch: {}
  # Automatic trigger after each release
  # Note: Triggers on both successes and failures (see conditional below)
  workflow_run:
    workflows:
      - release
    types:
      - completed
jobs:
  build_images:
    name: Build Images
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event.workflow_run.conclusion == null
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build api-server image
        run: |
          cd images/
          make api-server

      - name: Build api-server image with sample data
        run: |
          cd images/
          make api-server-with-data

      - name: Publish images
        run: |
          cd images
          make api-server-push
          make api-server-with-data-push
